In [95]:
def myfunction(x):
    print(x)
myfunction('helo')

helo


In [96]:
x = 10
y = "python is fun"
z = 144**0.5==12
print(x)
print(y)
print(z)

10
python is fun
True


In [97]:
x = "Helo"
y=x
y=y.upper()
print(x)
print(y)

Helo
HELO


In [98]:
x = [1,2,3]
print(x)
y=x
y.append(4)
print(y)

[1, 2, 3]
[1, 2, 3, 4]


In [99]:
my_list = ["Lesson", 5, "Is Fun", True]
print(my_list)

['Lesson', 5, 'Is Fun', True]


In [100]:
second_list=[]
second_list.append("Helo Im Long")
print(second_list)

['Helo Im Long']


In [101]:
num_list = [1,3,5,7,9]
print(len(num_list))
print(max(num_list))
print(min(num_list))
print(sum(num_list))
print(sum(num_list)/len(num_list))
num_list.count(3) #dem so lan xuat hien

5
9
1
25
5.0


1

In [102]:
new_list = [1,2,5,3,6,8,7]
new_list.reverse()
print("Reversed list", new_list)
new_list.sort(reverse=True)
print("Sort list", new_list)

Reversed list [7, 8, 6, 3, 5, 2, 1]
Sort list [8, 7, 6, 5, 3, 2, 1]


In [103]:
another_list=["Helo","Im","Long","Handsome","haha","a","b"]
print(another_list[0])
print(another_list[2])
print(another_list[-3])


Helo
Long
haha


In [104]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]
print(nested_list[1][2])
# vi tri 1, ô thứ 2

6


a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array

In [105]:
my_slice=another_list[1:3]
print(my_slice)
my_slice1=another_list[:2]
print(my_slice1)
my_slice2=another_list[2:]
print(my_slice2)
my_slice3=another_list[1:5:2] # từ 1 đến 4, sau đó xét khoảng 1 đến 5, lấy vị trí 2
print(my_slice3)

['Im', 'Long']
['Helo', 'Im']
['Long', 'Handsome', 'haha', 'a', 'b']
['Im', 'Handsome']


In [106]:
my_slice=another_list[::-1]
print(my_slice)

['b', 'a', 'haha', 'Handsome', 'Long', 'Im', 'Helo']


In [107]:
another_list=[1,2,3,4,5,6,7]
print(another_list)
next_itemm=another_list.pop(1)
print(next_itemm)
print(another_list)

[1, 2, 3, 4, 5, 6, 7]
2
[1, 3, 4, 5, 6, 7]


In [108]:
list1 = [1,2,3]
list2 = list1.copy()
list1.append(4)
print("Lst1", list1)
print("Lst2", list2)

Lst1 [1, 2, 3, 4]
Lst2 [1, 2, 3]


In [109]:
list1 = [1,2,3]
list2 = ["List within a list", list1]
list3 = list2.copy()
print("Before appending to list1")
print("List2:",list2)
print("List3:",list3)
print("After appending to list1")
list1.append(4)
print("List2:",list2)
print("List3:",list3)

Before appending to list1
List2: ['List within a list', [1, 2, 3]]
List3: ['List within a list', [1, 2, 3]]
After appending to list1
List2: ['List within a list', [1, 2, 3, 4]]
List3: ['List within a list', [1, 2, 3, 4]]


In [110]:
import copy
list1 = [1,2,3]
list2 = copy.deepcopy(list1) #sao chép y như ban đầu, ko thay đổi
list3 = list1
print(list2)
list1.append(4)
print(list2)
print(list3)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]


In [111]:
my_tuple = (1,3,5)
print(my_tuple)

(1, 3, 5)


In [112]:
# convert từ list sang tuples
# cant append and del from tuples
my_lst = [2,4,6,1]
my_tuples = tuple(my_lst)
print(my_tuples)
my_tuples[2]
my_tuples[2:4]

(2, 4, 6, 1)


(6, 1)

In [113]:
multiline_string = """I am
a multiline
string!
"""
print(multiline_string.splitlines())

['I am', 'a multiline', 'string!']


In [114]:
"xXxxBuyNowBxxxXX".strip("XxB")

'uyNow'

In [115]:
" ".join(["Helo", "can", "I", "join"])

'Helo can I join'

In [116]:
name="Long"
age=22
print(f"My name is {name} and I am {age} year old")
template_string=("My name is {} and I am {} year old")
template_string.format(name, age)


My name is Long and I am 22 year old


'My name is Long and I am 22 year old'

In [117]:
my_dict = {
    "Name":"Long",
    "age": 22,
    "city":"HCM"
}
print(my_dict)


{'Name': 'Long', 'age': 22, 'city': 'HCM'}


In [118]:
my_dict["Name"]
my_dict["Gender:"] = "Male"
print(my_dict)

{'Name': 'Long', 'age': 22, 'city': 'HCM', 'Gender:': 'Male'}


In [119]:
print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())

dict_keys(['Name', 'age', 'city', 'Gender:'])
dict_values(['Long', 22, 'HCM', 'Male'])
dict_items([('Name', 'Long'), ('age', 22), ('city', 'HCM'), ('Gender:', 'Male')])


In [120]:
import pandas as pd
my_table_dict = {
    "name":["Joe","Bob","Harry"],
    "age":[18,20,21],
    "city":["Tokyo","HCM","NY"]
}
df = pd.DataFrame(my_table_dict)
print(df)

    name  age   city
0    Joe   18  Tokyo
1    Bob   20    HCM
2  Harry   21     NY


In [121]:
my_set1 = {1,2,3,3,4,5}
set2 = {1,2}
print(my_set1)
print(my_set1.union())
print(my_set1.intersection(set2))
print(my_set1.difference(set2))
print(my_set1.issubset(set2))
print(set2.issubset(my_set1))

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{1, 2}
{3, 4, 5}
False
True


In [122]:
myList = [1,1,2,2,3,4,5,6,6,7]
set(myList)

{1, 2, 3, 4, 5, 6, 7}

In [123]:
myset = {1,2,3,4,3,2}
print(myset)

{1, 2, 3, 4}


In [124]:
import numpy as np
first_list = [1,2,3]
first_array = np.array(first_list)
# type(my_array)
print(first_array)
second_list=[4,5,6]
second_array = np.array([first_list,second_list])
print(second_array)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [125]:
# ma trận n cột, m hàng, k giá trị chỉ mục đường chéo
np.eye(N=3,M=5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [126]:
one_d_array = np.array([1,2,3,4,5,6])
two_d_array = np.array([one_d_array, one_d_array+6, one_d_array+12])
# print(two_d_array)
# print(two_d_array[1,4])
# print(two_d_array[1:,4:]) # lấy từ row 1, vị trí thứ 4 trở đi
print(two_d_array[::-1,::-1])

[[18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [127]:
np.reshape(a=two_d_array,newshape=(6,3))
#reshape: định hình lại mảng
#newshape: mảng mới
# ngoài ra có thể xài C-style(theo row) hoặc Fortran-style(theo columns) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [128]:
import numpy as np
array_to_join = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.concatenate((two_d_array,array_to_join),axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

In [129]:
two_d_array + 100
# có thể làm thêm nhân chia cộng trừ, chẵn lẻ

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118]])

In [130]:
small_array = np.array([[1,2],[3,4]])
small_array+small_array
# có thể làm thêm nhân chia cộng trừ

array([[2, 4],
       [6, 8]])

In [131]:
np.average(two_d_array)
np.mean(two_d_array)

9.5

PANDAS

In [132]:
import pandas as pd
import numpy as np
my_series = pd.Series(
    data=[2,3,4,5],
    index=["a","b","c","d"]
    )
my_series

a    2
b    3
c    4
d    5
dtype: int64

In [133]:
my_dict = {"x":2,"y":3,"z":4,"w":5}
my_series = pd.Series(my_dict)
my_series

x    2
y    3
z    4
w    5
dtype: int64

In [134]:
my_series["x"]

2

In [135]:
my_series[1:3]

y    3
z    4
dtype: int64

In [136]:
# Create dictionary with some values
my_dict={
    "name":["Bob","Alice","Frans"],
    "age":[23,32,39],
    "weight":[70,80,76],
    "height":pd.Series([175,180,178], index=["Bob","Alice","Frans"]),
    "gender":["M","F","M"]
}
df=pd.DataFrame(my_dict) #Convert to Dataframe
df #Show

name  age  weight  height gender
Bob      Bob   23      70     175      M
Alice  Alice   32      80     180      F
Frans  Frans   39      76     178      M

In [137]:
print(df["name"])
print(df.age)

Bob        Bob
Alice    Alice
Frans    Frans
Name: name, dtype: object
Bob      23
Alice    32
Frans    39
Name: age, dtype: int64


In [138]:
df["IQ"]=[90,100,200]
df["Married"]=False
df

name  age  weight  height gender   IQ  Married
Bob      Bob   23      70     175      M   90    False
Alice  Alice   32      80     180      F  100    False
Frans  Frans   39      76     178      M  200    False

In [139]:
df["College"] = pd.Series(["Harvard"],index=["Bob"])
df

name  age  weight  height gender   IQ  Married  College
Bob      Bob   23      70     175      M   90    False  Harvard
Alice  Alice   32      80     180      F  100    False      NaN
Frans  Frans   39      76     178      M  200    False      NaN

In [150]:
df.loc["Bob"]

name           Bob
age             23
weight          70
height         175
gender           M
IQ              90
Married      False
College    Harvard
Name: Bob, dtype: object

In [152]:
df.loc["Bob":"Alice", "weight":"IQ"]

weight  height gender   IQ
Bob        70     175      M   90
Alice      80     180      F  100

In [156]:
df.iloc[1] #get row 1

name       Alice
age           32
weight        80
height       180
gender         F
IQ           100
Married    False
College      NaN
Name: Alice, dtype: object

In [157]:
df.iloc[0,5] #get row 0, column 5 : IQ

90

In [168]:
df.iloc[0:2,5:8] # lấy row 0,1, từ vị trí columns 5 đến 7

IQ  Married  College
Bob     90    False  Harvard
Alice  100    False      NaN

In [178]:
boonlean_index = df["age"]>30
df[boonlean_index]

name  age  weight  height gender   IQ  Married College
Alice  Alice   32      80     180      F  100    False     NaN
Frans  Frans   39      76     178      M  200    False     NaN

In [183]:
titanic_train = pd.read_csv("train.csv")
# type(titanic_train)
# print(titanic_train)
titanic_train.shape

(891, 11)

In [184]:
titanic_train.head(6) #6 đầu tiên

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   
5         0       3                                   Moran, Mr. James   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S  
5    male   NaN      0      0            330877   8.4583   NaN        Q

In [185]:
titanic_train.tail(6) # 6 cuối cùng

survived  pclass                                      name     sex   age  \
885         0       3      Rice, Mrs. William (Margaret Norton)  female  39.0   
886         0       2                     Montvila, Rev. Juozas    male  27.0   
887         1       1              Graham, Miss. Margaret Edith  female  19.0   
888         0       3  Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889         1       1                     Behr, Mr. Karl Howell    male  26.0   
890         0       3                       Dooley, Mr. Patrick    male  32.0   

     sibsp  parch      ticket    fare cabin embarked  
885      0      5      382652  29.125   NaN        Q  
886      0      0      211536  13.000   NaN        S  
887      0      0      112053  30.000   B42        S  
888      1      2  W./C. 6607  23.450   NaN        S  
889      0      0      111369  30.000  C148        C  
890      0      0      370376   7.750   NaN        Q

In [188]:
a=titanic_train["name"]
a[0:10]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: name, dtype: object

In [189]:
titanic_train.columns

Index(['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked'],
      dtype='object')

In [191]:
titanic_train.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [194]:
np.mean(titanic_train,axis=0) 
#axist=0 là lấy theo hàng dọc, axist=1 là lấy theo hàng ngang

C:\Users\baolo\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


survived     0.383838
pclass       2.308642
age         29.699118
sibsp        0.523008
parch        0.381594
fare        32.204208
dtype: float64