READING AND WRITING DATA

In [3]:
import os
os.getcwd() # location

'c:\\Users\\baolo\\OneDrive\\Desktop\\python'

In [4]:
os.listdir('c:\\Users\\baolo\\OneDrive\\Desktop\\python')

['.git',
 'Book1.xlsx',
 'DSV.xls',
 'DSV.xlsx',
 'PythonBasic_1.ipynb',
 'PythonBasic_2.ipynb',
 'Test-Matplotlib.py',
 'train',
 'train.csv',
 'venv']

READING CSV AND TSV Files

In [5]:
import pandas as pd
titanic_train=pd.read_csv('train.csv')
titanic_train.head(6)

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   
5         0       3                                   Moran, Mr. James   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S  
5    male   NaN      0      0            330877   8.4583   NaN        Q

In [6]:
from openpyxl import Workbook
draft=pd.read_excel('Book1.xlsx',sheet_name='Sheet1')
draft

Player  Draft_Express  CBS  CBS 2  CBS 3  BleacherReport  Sl
0  Karl-Anthony Towns              1    1      1      1               1   1
1        Jahil Okafor              2    2      2      2               2   2
2            Nguyuyễn              2    3      1      4               4   1

In [7]:
draft.to_csv("draft-saved.csv")
os.listdir("c:\\Users\\baolo\\OneDrive\\Desktop\\python")

['.git',
 'Book1.xlsx',
 'draft-saved.csv',
 'DSV.xls',
 'DSV.xlsx',
 'PythonBasic_1.ipynb',
 'PythonBasic_2.ipynb',
 'Test-Matplotlib.py',
 'train',
 'train.csv',
 'venv']

Control Flow (if, else, for, while)

In [8]:
x=10
y=5
if x>y:
    print("x is greater than y")

x is greater than y


In [9]:
x=10
y=20
if x>y:
    print('x is greater than y')
else:
    print('y is greater than x')

y is greater than x


In [10]:
x=10
y=10
if x>y:
    print('x is greater than y')
elif x==y:
    print('y and x are equals')
else:
    print('y is greater than x')

y and x are equals


FOR LOOPS

In [11]:
my_sequence=range(0,101,10) # make list
for number in my_sequence: #create new loop
    print(number)

0
10
20
30
40
50
60
70
80
90
100


In [12]:
for i in my_sequence:
    if i<50:
        continue            #skip numbers < 50
    print(i)

50
60
70
80
90
100


In [13]:
#while sẽ chạy lần lượt từ đầu, if sẽ chạy 1 lần 
x=5
iters=1
while iters<x:
    print("Study")
    iters+=1

Study
Study
Study
Study


The np.where() Function

In [14]:
import numpy as np
#draw 25 random numbers from 1-25
my_data=np.random.uniform(1,26,25) #trả đổi tượng về dưới dạng liệt kê

for index,number in enumerate(my_data): #enumerate trả về dưới dạng liệt kê
    if number <10:
        my_data[index] = 0
print(my_data)

[10.95817438 11.24832174 24.98053902 19.09211205  0.         17.67096807
 22.74240728  0.         15.15140344 11.44261023 15.88379104 11.68417067
  0.         11.7820632  25.80542704  0.         15.95295222 24.47356397
  0.          0.         14.76729999 23.43275798 24.25618259 25.17146141
  0.        ]


In [15]:
my_data=np.random.uniform(-1,1,25)
my_data=np.where(
    my_data<0,              #A logical test
    0,                      #Value to set if true
    my_data)                #Value to set if false
print(my_data)

[0.25059474 0.         0.         0.83964838 0.         0.
 0.         0.         0.         0.5441368  0.32730424 0.
 0.         0.7318929  0.95553152 0.4218224  0.         0.48042492
 0.         0.89926463 0.         0.         0.         0.2144231
 0.56192236]


FUNCTIONS

In [16]:
def my_function(arg1,arg2):
    return arg1+arg2
my_function(5,10)

15

In [17]:
def func2(ar1,ar2):
    if ar1>3 and ar2>1:
        return ar2          #giong print"ar2"
func2(4,5) 

5

In [18]:
def sum_3_item(x,y,z,printarc=False):
    if printarc:
        print(x,y,z)
    return 1
sum_3_item(1,2,3)

1

In [19]:
sum_3_item(1,4,5,True)

1 4 5


1

In [20]:
def sum_many_args(*args): #truyền nhiều tham số vào hàm
    print(type(args))
    return sum(args)
sum_many_args(1,2,3,4,5)

<class 'tuple'>


15

In [21]:
def sum_keywords(**kwargs):
    print(type(kwargs))
    print(kwargs)
    print(sum(kwargs.values())) #kwargs.value: lấy giá trị của biến a,b
sum_keywords(a=100,b=200)

<class 'dict'>
{'a': 100, 'b': 200}
300


LAMBDA FUNCTION


In [22]:
#lambda tham_so: bieu_thuc
#Hàm Lambda có thể có nhiều tham số nhưng chỉ có 1 biểu thức.
lambda x,y:y+x

<function __main__.<lambda>(x, y)>

In [23]:
my_function2 = lambda x,y:y+x
my_function2(2,3)

5

In [24]:
#using map() without lambda function
#duyệt tất cả các phần tử của một iterable (list, tuple, dictionary...) 
#qua một hàm cho trước và trả vềmột list kết quả sau khi thực thi
def square(x):
    return x**2
my_map=map(square,[1,2,3,4,5])
for item in my_map:
    print(item)

1
4
9
16
25


In [25]:
#using map() with lambda function
my_map=map(lambda x:x**2,[1,2,3,4,5])
for item in my_map:
    print(item)

1
4
9
16
25


 List Comprehensions

In [26]:
my_list=[]
for numbers in range(1,21):
    my_list.append(numbers)
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [27]:
my_list=[number for number in range(1,21)]
#number: điều kiện thực thi, ví dụ number.upper()
#gọi vòng lặp
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [28]:
my_list3 = [number for number in range(1,101) if number % 5==0]
print(my_list3)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [29]:
combined=[a+b for a in ["life "] for b in ["study"]]
print(combined)

['life study']


In [30]:
combined = [a+b for a in "life" for b in "study"]
non_nested = [letter[0] for letter in combined]
print(non_nested)

['l', 'l', 'l', 'l', 'l', 'i', 'i', 'i', 'i', 'i', 'f', 'f', 'f', 'f', 'f', 'e', 'e', 'e', 'e', 'e']


Dictionary Comprehensions

In [31]:
words = ["life","is","study"]
word_lengt_dict = {}
for word in words:
    word_lengt_dict[word] = len(word)
print(word_lengt_dict) 

{'life': 4, 'is': 2, 'study': 5}


In [32]:
words = ["life","is","study"]
word_lengt_dict2 = {word: len(word) for word in words}
print(word_lengt_dict2)

{'life': 4, 'is': 2, 'study': 5}


In [33]:
number_list = [1,2,3]
strList = ['one','two','three']
result = zip(number_list,strList)
for i in result:
    print(i)

(1, 'one')
(2, 'two')
(3, 'three')


In [34]:
words = ["life","is","study"]
words_lenght = [4,2,5]
result1_dict = {key:value for (key,value) in zip(words,words_lenght)}
print(result1_dict)

{'life': 4, 'is': 2, 'study': 5}


Exploring and Cleaning Data

In [35]:
import numpy as np
import pandas as pd
import os
titanic_train = pd.read_csv("train.csv")
titanic_train.shape

(891, 11)

In [36]:
#????????????????????????????????????????
categorical = titanic_train.dtypes[titanic_train.dtypes=="object"].index
print(categorical)
titanic_train[categorical].describe()

Index(['name', 'sex', 'ticket', 'cabin', 'embarked'], dtype='object')


name   sex  ticket    cabin embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [37]:
sorted(titanic_train["name"]) [0:10]

['Abbing, Mr. Anthony',
 'Abbott, Mr. Rossmore Edward',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Abelson, Mr. Samuel',
 'Abelson, Mrs. Samuel (Hannah Wizosky)',
 'Adahl, Mr. Mauritz Nils Martin',
 'Adams, Mr. John',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Aks, Mrs. Sam (Leah Rosen)',
 'Albimona, Mr. Nassef Cassem']

In [38]:
titanic_train["name"].describe()

count                         891
unique                        891
top       Braund, Mr. Owen Harris
freq                            1
Name: name, dtype: object

In [39]:
titanic_train["ticket"][0:10]

0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
5              330877
6               17463
7              349909
8              347742
9              237736
Name: ticket, dtype: object

In [45]:
titanic_train["survived"].describe()

count    891.000000
mean       0.383838
std        0.486592
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: survived, dtype: float64

In [56]:
#chọn categori 
new_survived = pd.Categorical(titanic_train["sibsp"]) 

#đổi tên các thành phần trong categori đó
new_survived = new_survived.rename_categories(["Died","Survived","life","style","study","cat","dog"]) 

#liệt kê tổng thành phần 
new_survived.describe()

counts     freqs
categories                  
0              608  0.682379
1              209  0.234568
2               28  0.031425
3               16  0.017957
4               18  0.020202
5                5  0.005612
8                7  0.007856

In [66]:
new_Pclass = pd.Categorical(titanic_train["pclass"])
new_Pclass = new_Pclass.rename_categories(["Class1","Class2","Class3"])
new_Pclass.describe()

counts     freqs
categories                  
Class1         216  0.242424
Class2         184  0.206510
Class3         491  0.551066

In [77]:
titanic_train["cabin"].unique() # các giá trị trong cột cabin

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [116]:
char_cabin = titanic_train["cabin"].astype(str)  #Các dữ liệu dạng phân loại thường được biểu diễn dưới dạng text.
char_cabin = np.array([char[0] for char in char_cabin])
new_char = pd.Categorical(char_cabin)   #pd.Categorical là danh mục dữ liệu phân loại
new_char.describe()

counts     freqs
categories                  
A10              1  0.001122
A14              1  0.001122
A16              1  0.001122
A19              1  0.001122
A20              1  0.001122
...            ...       ...
F38              1  0.001122
F4               2  0.002245
G6               4  0.004489
T                1  0.001122
nan            687  0.771044

[148 rows x 2 columns]

In [119]:
gender1 = titanic_train["sex"]
gender1 = pd.Categorical(gender1)
gender1.describe()


counts     freqs
categories                  
female         314  0.352413
male           577  0.647587

In [121]:
dummy_vector = pd.Series([1,2,3,4,None]) 
dummy_vector.isnull() 
# kiểm tra giá trị null
# isnull chạy trong library pandas
# Series là một đối tượng giống mảng một chiều,
# Nó có thể được xem như là một cấu trúc dữ liệu với hai mảng: 
# một lưu chỉ mục, cái còn lại lưu dữ liệu, ví dụ: S = pd.Series(np.random.randint(100,size = 5))

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [130]:
# np.wheregiống như hỏi " cho tôi biết nơi nào trong mảng này, 
# các mục thỏa mãn một điều kiện nhất định ".
# xuất ra các VỊ TRÍ của điều kiện

a =np.arange(5,10)
np.where(a<8)


(array([0, 1, 2], dtype=int64),)

In [147]:
missing = np.where(titanic_train["embarked"].isnull()==True)
missing
#isnull: rỗng thì trả về true, có giá trị thì false

(array([ 61, 829], dtype=int64),)

In [148]:
len(missing[0]) #đếm xem có bao nhiêu ô NaN( Not a Number)

2

In [155]:
import matplotlib.pyplot as pt
