In [38]:
def myfunction(x):
    print(x)
myfunction('helo')

helo


In [39]:
x = 10
y = "python is fun"
z = 144**0.5==12
print(x)
print(y)
print(z)

10
python is fun
True


In [40]:
x = "Helo"
y=x
y=y.upper()
print(x)
print(y)

Helo
HELO


In [54]:
x = [1,2,3]
print(x)
y=x
y.append(4)
print(y)

[1, 2, 3]
[1, 2, 3, 4]


In [42]:
my_list = ["Lesson", 5, "Is Fun", True]
print(my_list)

['Lesson', 5, 'Is Fun', True]


In [48]:
second_list=[]
second_list.append("Helo Im Long")
print(second_list)

['Helo Im Long']


In [64]:
num_list = [1,3,5,7,9]
print(len(num_list))
print(max(num_list))
print(min(num_list))
print(sum(num_list))
print(sum(num_list)/len(num_list))
num_list.count(3) #dem so lan xuat hien

5
9
1
25
5.0


1

In [73]:
new_list = [1,2,5,3,6,8,7]
new_list.reverse()
print("Reversed list", new_list)
new_list.sort(reverse=True)
print("Sort list", new_list)

Reversed list [7, 8, 6, 3, 5, 2, 1]
Sort list [8, 7, 6, 5, 3, 2, 1]


In [134]:
another_list=["Helo","Im","Long","Handsome","haha","a","b"]
print(another_list[0])
print(another_list[2])
print(another_list[-3])


Helo
Long
haha


In [81]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]
print(nested_list[1][2])
# vi tri 1, ô thứ 2

6


a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array

In [136]:
my_slice=another_list[1:3]
print(my_slice)
my_slice1=another_list[:2]
print(my_slice1)
my_slice2=another_list[2:]
print(my_slice2)
my_slice3=another_list[1:5:2] # từ 1 đến 4, sau đó xét khoảng 1 đến 5, lấy vị trí 2
print(my_slice3)

['Im', 'Long']
['Helo', 'Im']
['Long', 'Handsome', 'haha', 'a', 'b']
['Im', 'Handsome']


In [137]:
my_slice=another_list[::-1]
print(my_slice)

['b', 'a', 'haha', 'Handsome', 'Long', 'Im', 'Helo']


In [158]:
another_list=[1,2,3,4,5,6,7]
print(another_list)
next_itemm=another_list.pop(1)
print(next_itemm)
print(another_list)

[1, 2, 3, 4, 5, 6, 7]
2
[1, 3, 4, 5, 6, 7]


In [159]:
list1 = [1,2,3]
list2 = list1.copy()
list1.append(4)
print("Lst1", list1)
print("Lst2", list2)

Lst1 [1, 2, 3, 4]
Lst2 [1, 2, 3]


In [163]:
list1 = [1,2,3]
list2 = ["List within a list", list1]
list3 = list2.copy()
print("Before appending to list1")
print("List2:",list2)
print("List3:",list3)
print("After appending to list1")
list1.append(4)
print("List2:",list2)
print("List3:",list3)

Before appending to list1
List2: ['List within a list', [1, 2, 3]]
List3: ['List within a list', [1, 2, 3]]
After appending to list1
List2: ['List within a list', [1, 2, 3, 4]]
List3: ['List within a list', [1, 2, 3, 4]]


In [165]:
import copy
list1 = [1,2,3]
list2 = copy.deepcopy(list1) #sao chép y như ban đầu, ko thay đổi
list3 = list1
print(list2)
list1.append(4)
print(list2)
print(list3)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]


In [166]:
my_tuple = (1,3,5)
print(my_tuple)

(1, 3, 5)


In [169]:
# convert từ list sang tuples
# cant append and del from tuples
my_lst = [2,4,6,1]
my_tuples = tuple(my_lst)
print(my_tuples)
my_tuples[2]
my_tuples[2:4]

(2, 4, 6, 1)


(6, 1)

In [187]:
multiline_string = """I am
a multiline
string!
"""
print(multiline_string.splitlines())

['I am', 'a multiline', 'string!']


In [202]:
"xXxxBuyNowBxxxXX".strip("XxB")

'uyNow'

In [205]:
" ".join(["Helo", "can", "I", "join"])

'Helo can I join'

In [232]:
name="Long"
age=22
print(f"My name is {name} and I am {age} year old")
template_string=("My name is {} and I am {} year old")
template_string.format(name, age)


My name is Long and I am 22 year old


'My name is Long and I am 22 year old'

In [238]:
my_dict = {
    "Name":"Long",
    "age": 22,
    "city":"HCM"
}
print(my_dict)


{'Name': 'Long', 'age': 22, 'city': 'HCM'}


In [239]:
my_dict["Name"]
my_dict["Gender:"] = "Male"
print(my_dict)

{'Name': 'Long', 'age': 22, 'city': 'HCM', 'Gender:': 'Male'}


In [243]:
print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())

dict_keys(['Name', 'age', 'city', 'Gender:'])
dict_values(['Long', 22, 'HCM', 'Male'])
dict_items([('Name', 'Long'), ('age', 22), ('city', 'HCM'), ('Gender:', 'Male')])


In [250]:
import pandas as pd
my_table_dict = {
    "name":["Joe","Bob","Harry"],
    "age":[18,20,21],
    "city":["Tokyo","HCM","NY"]
}
df = pd.DataFrame(my_table_dict)
print(df)

    name  age   city
0    Joe   18  Tokyo
1    Bob   20    HCM
2  Harry   21     NY


In [262]:
my_set1 = {1,2,3,3,4,5}
set2 = {1,2}
print(my_set1)
print(my_set1.union())
print(my_set1.intersection(set2))
print(my_set1.difference(set2))
print(my_set1.issubset(set2))
print(set2.issubset(my_set1))

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{1, 2}
{3, 4, 5}
False
True


In [259]:
myList = [1,1,2,2,3,4,5,6,6,7]
set(myList)

{1, 2, 3, 4, 5, 6, 7}

In [261]:
myset = {1,2,3,4,3,2}
print(myset)

{1, 2, 3, 4}


In [8]:
import numpy as np
first_list = [1,2,3]
first_array = np.array(first_list)
# type(my_array)
print(first_array)
second_list=[4,5,6]
second_array = np.array([first_list,second_list])
print(second_array)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [12]:
# ma trận n cột, m hàng, k giá trị chỉ mục đường chéo
np.eye(N=3,M=5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [11]:
one_d_array = np.array([1,2,3,4,5,6])
two_d_array = np.array([one_d_array, one_d_array+6, one_d_array+12])
# print(two_d_array)
# print(two_d_array[1,4])
# print(two_d_array[1:,4:]) # lấy từ row 1, vị trí thứ 4 trở đi
print(two_d_array[::-1,::-1])

[[18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


In [13]:
np.reshape(a=two_d_array,newshape=(6,3))
#reshape: định hình lại mảng
#newshape: mảng mới
# ngoài ra có thể xài C-style(theo row) hoặc Fortran-style(theo columns) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
import numpy as np
array_to_join = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.concatenate((two_d_array,array_to_join),axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

In [19]:
two_d_array + 100
# có thể làm thêm nhân chia cộng trừ, chẵn lẻ

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118]])

In [22]:
small_array = np.array([[1,2],[3,4]])
small_array+small_array
# có thể làm thêm nhân chia cộng trừ

array([[2, 4],
       [6, 8]])

In [24]:
np.average(two_d_array)
np.mean(two_d_array)

9.5

PANDAS

In [26]:
import pandas as pd
import numpy as np
my_series = pd.Series(
    data=[2,3,4,5],
    index=["a","b","c","d"]
    )
my_series

a    2
b    3
c    4
d    5
dtype: int64

In [28]:
my_dict = {"x":2,"y":3,"z":4,"w":5}
my_series = pd.Series(my_dict)
my_series

x    2
y    3
z    4
w    5
dtype: int64